/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    authors: Author;
    categories: Category;
    countries: Country;
    'car-makes': CarMake;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    'car-makes': CarMakesSelect<false> | CarMakesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'de' | 'uk' | 'pl' | 'it' | 'ru' | 'fr' | 'es')
    | ('en' | 'de' | 'uk' | 'pl' | 'it' | 'ru' | 'fr' | 'es')[];
  globals: {
    'site-config': SiteConfig;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
  };
  locale: 'en' | 'de' | 'uk' | 'pl' | 'it' | 'ru' | 'fr' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Auto-generated from title if left empty.
   */
  slug: string;
  publishedAt?: string | null;
  content?:
    | (
        | {
            variant: 'centered' | 'split' | 'stacked';
            dark?: boolean | null;
            fullHeight?: boolean | null;
            glow?: boolean | null;
            /**
             * Centered/stacked: shows below text. Split: shows on right side.
             */
            formType?: ('none' | 'vin' | 'contact') | null;
            /**
             * Small label above heading
             */
            tag?: string | null;
            tagLevel?: ('span' | 'h2' | 'h3' | 'h4' | 'p') | null;
            /**
             * Main heading text
             */
            title: string;
            /**
             * Bold gradient portion of heading
             */
            highlight?: string | null;
            subtitle?: string | null;
            /**
             * Heading after description, before CTAs (e.g. "We'll be happy to assist you!")
             */
            secondaryHeading?: string | null;
            secondaryHeadingLevel?: ('h2' | 'h3' | 'h4' | 'p') | null;
            bullets?:
              | {
                  text: string;
                  tag?: ('span' | 'h2' | 'h3' | 'h4' | 'h5' | 'p') | null;
                  id?: string | null;
                }[]
              | null;
            features?:
              | {
                  icon?: {
                    source?: ('preset' | 'custom') | null;
                    preset?:
                      | (
                          | 'car'
                          | 'car-front'
                          | 'bike'
                          | 'truck'
                          | 'shield-check'
                          | 'shield'
                          | 'lock'
                          | 'lock-open'
                          | 'triangle-alert'
                          | 'siren'
                          | 'file-text'
                          | 'clipboard-check'
                          | 'file-search'
                          | 'circle-check'
                          | 'circle-x'
                          | 'search'
                          | 'eye'
                          | 'scan'
                          | 'gauge'
                          | 'trending-up'
                          | 'trending-down'
                          | 'database'
                          | 'bar-chart-3'
                          | 'wallet'
                          | 'credit-card'
                          | 'tag'
                          | 'receipt'
                          | 'mail'
                          | 'phone'
                          | 'headphones'
                          | 'message-circle'
                          | 'zap'
                          | 'wrench'
                          | 'globe'
                          | 'mouse-pointer-click'
                          | 'download'
                          | 'link'
                          | 'info'
                          | 'chevron-right'
                          | 'star'
                          | 'heart'
                          | 'house'
                          | 'map-pin'
                          | 'clock'
                          | 'calendar'
                          | 'user'
                          | 'users'
                          | 'building'
                          | 'pencil'
                          | 'hash'
                          | 'list'
                          | 'factory'
                          | 'circle-dot'
                        )
                      | null;
                    /**
                     * Any Lucide icon name (e.g. "package-check")
                     */
                    custom?: string | null;
                  };
                  text: string;
                  tag?: ('span' | 'h2' | 'h3' | 'h4' | 'h5' | 'p') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Right-side image for split variant (580×660 recommended)
             */
            heroImage?: (number | null) | Media;
            /**
             * Optional background image
             */
            backgroundImage?: (number | null) | Media;
            ctas?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'secondary') | null;
                  rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
                  newTab?: boolean | null;
                  isExternal?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            helperLinks?:
              | {
                  label: string;
                  href: string;
                  style?: ('arrow' | 'pill') | null;
                  /**
                   * Lucide icon
                   */
                  icon?: string | null;
                  rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
                  newTab?: boolean | null;
                  isExternal?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'page-hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            items: {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqs';
          }
      )[]
    | null;
  exitPopup?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    description?: string | null;
    ctaText?: string | null;
    offerImage?: (number | null) | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    metaRobots?: ('index, follow' | 'noindex, follow' | 'index, nofollow' | 'noindex, nofollow') | null;
    canonicalURL?: string | null;
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Auto-generated from title if left empty.
   */
  slug: string;
  publishedAt?: string | null;
  /**
   * Minutes
   */
  readTime?: number | null;
  author: number | Author;
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedMode?: ('dynamic' | 'manual') | null;
  relatedPosts?: (number | Post)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    metaRobots?: ('index, follow' | 'noindex, follow' | 'index, nofollow' | 'noindex, nofollow') | null;
    canonicalURL?: string | null;
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  email: string;
  image?: (number | null) | Media;
  socials?: {
    x?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
    website?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  label: string;
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  /**
   * URL-safe identifier. Auto-generated from title if left empty.
   */
  slug: string;
  status?: ('active' | 'inactive') | null;
  content?:
    | (
        | {
            variant: 'centered' | 'split' | 'stacked';
            dark?: boolean | null;
            fullHeight?: boolean | null;
            glow?: boolean | null;
            /**
             * Centered/stacked: shows below text. Split: shows on right side.
             */
            formType?: ('none' | 'vin' | 'contact') | null;
            /**
             * Small label above heading
             */
            tag?: string | null;
            tagLevel?: ('span' | 'h2' | 'h3' | 'h4' | 'p') | null;
            /**
             * Main heading text
             */
            title: string;
            /**
             * Bold gradient portion of heading
             */
            highlight?: string | null;
            subtitle?: string | null;
            /**
             * Heading after description, before CTAs (e.g. "We'll be happy to assist you!")
             */
            secondaryHeading?: string | null;
            secondaryHeadingLevel?: ('h2' | 'h3' | 'h4' | 'p') | null;
            bullets?:
              | {
                  text: string;
                  tag?: ('span' | 'h2' | 'h3' | 'h4' | 'h5' | 'p') | null;
                  id?: string | null;
                }[]
              | null;
            features?:
              | {
                  icon?: {
                    source?: ('preset' | 'custom') | null;
                    preset?:
                      | (
                          | 'car'
                          | 'car-front'
                          | 'bike'
                          | 'truck'
                          | 'shield-check'
                          | 'shield'
                          | 'lock'
                          | 'lock-open'
                          | 'triangle-alert'
                          | 'siren'
                          | 'file-text'
                          | 'clipboard-check'
                          | 'file-search'
                          | 'circle-check'
                          | 'circle-x'
                          | 'search'
                          | 'eye'
                          | 'scan'
                          | 'gauge'
                          | 'trending-up'
                          | 'trending-down'
                          | 'database'
                          | 'bar-chart-3'
                          | 'wallet'
                          | 'credit-card'
                          | 'tag'
                          | 'receipt'
                          | 'mail'
                          | 'phone'
                          | 'headphones'
                          | 'message-circle'
                          | 'zap'
                          | 'wrench'
                          | 'globe'
                          | 'mouse-pointer-click'
                          | 'download'
                          | 'link'
                          | 'info'
                          | 'chevron-right'
                          | 'star'
                          | 'heart'
                          | 'house'
                          | 'map-pin'
                          | 'clock'
                          | 'calendar'
                          | 'user'
                          | 'users'
                          | 'building'
                          | 'pencil'
                          | 'hash'
                          | 'list'
                          | 'factory'
                          | 'circle-dot'
                        )
                      | null;
                    /**
                     * Any Lucide icon name (e.g. "package-check")
                     */
                    custom?: string | null;
                  };
                  text: string;
                  tag?: ('span' | 'h2' | 'h3' | 'h4' | 'h5' | 'p') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Right-side image for split variant (580×660 recommended)
             */
            heroImage?: (number | null) | Media;
            /**
             * Optional background image
             */
            backgroundImage?: (number | null) | Media;
            ctas?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'secondary') | null;
                  rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
                  newTab?: boolean | null;
                  isExternal?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            helperLinks?:
              | {
                  label: string;
                  href: string;
                  style?: ('arrow' | 'pill') | null;
                  /**
                   * Lucide icon
                   */
                  icon?: string | null;
                  rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
                  newTab?: boolean | null;
                  isExternal?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'page-hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            items: {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqs';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    metaRobots?: ('index, follow' | 'noindex, follow' | 'index, nofollow' | 'noindex, nofollow') | null;
    canonicalURL?: string | null;
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-makes".
 */
export interface CarMake {
  id: number;
  name: string;
  /**
   * URL-safe identifier. Auto-generated from title if left empty.
   */
  slug: string;
  logo?: (number | null) | Media;
  status?: ('active' | 'inactive') | null;
  content?:
    | (
        | {
            variant: 'centered' | 'split' | 'stacked';
            dark?: boolean | null;
            fullHeight?: boolean | null;
            glow?: boolean | null;
            /**
             * Centered/stacked: shows below text. Split: shows on right side.
             */
            formType?: ('none' | 'vin' | 'contact') | null;
            /**
             * Small label above heading
             */
            tag?: string | null;
            tagLevel?: ('span' | 'h2' | 'h3' | 'h4' | 'p') | null;
            /**
             * Main heading text
             */
            title: string;
            /**
             * Bold gradient portion of heading
             */
            highlight?: string | null;
            subtitle?: string | null;
            /**
             * Heading after description, before CTAs (e.g. "We'll be happy to assist you!")
             */
            secondaryHeading?: string | null;
            secondaryHeadingLevel?: ('h2' | 'h3' | 'h4' | 'p') | null;
            bullets?:
              | {
                  text: string;
                  tag?: ('span' | 'h2' | 'h3' | 'h4' | 'h5' | 'p') | null;
                  id?: string | null;
                }[]
              | null;
            features?:
              | {
                  icon?: {
                    source?: ('preset' | 'custom') | null;
                    preset?:
                      | (
                          | 'car'
                          | 'car-front'
                          | 'bike'
                          | 'truck'
                          | 'shield-check'
                          | 'shield'
                          | 'lock'
                          | 'lock-open'
                          | 'triangle-alert'
                          | 'siren'
                          | 'file-text'
                          | 'clipboard-check'
                          | 'file-search'
                          | 'circle-check'
                          | 'circle-x'
                          | 'search'
                          | 'eye'
                          | 'scan'
                          | 'gauge'
                          | 'trending-up'
                          | 'trending-down'
                          | 'database'
                          | 'bar-chart-3'
                          | 'wallet'
                          | 'credit-card'
                          | 'tag'
                          | 'receipt'
                          | 'mail'
                          | 'phone'
                          | 'headphones'
                          | 'message-circle'
                          | 'zap'
                          | 'wrench'
                          | 'globe'
                          | 'mouse-pointer-click'
                          | 'download'
                          | 'link'
                          | 'info'
                          | 'chevron-right'
                          | 'star'
                          | 'heart'
                          | 'house'
                          | 'map-pin'
                          | 'clock'
                          | 'calendar'
                          | 'user'
                          | 'users'
                          | 'building'
                          | 'pencil'
                          | 'hash'
                          | 'list'
                          | 'factory'
                          | 'circle-dot'
                        )
                      | null;
                    /**
                     * Any Lucide icon name (e.g. "package-check")
                     */
                    custom?: string | null;
                  };
                  text: string;
                  tag?: ('span' | 'h2' | 'h3' | 'h4' | 'h5' | 'p') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Right-side image for split variant (580×660 recommended)
             */
            heroImage?: (number | null) | Media;
            /**
             * Optional background image
             */
            backgroundImage?: (number | null) | Media;
            ctas?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'secondary') | null;
                  rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
                  newTab?: boolean | null;
                  isExternal?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            helperLinks?:
              | {
                  label: string;
                  href: string;
                  style?: ('arrow' | 'pill') | null;
                  /**
                   * Lucide icon
                   */
                  icon?: string | null;
                  rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
                  newTab?: boolean | null;
                  isExternal?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'page-hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            items: {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqs';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    metaRobots?: ('index, follow' | 'noindex, follow' | 'index, nofollow' | 'noindex, nofollow') | null;
    canonicalURL?: string | null;
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'car-makes';
        value: number | CarMake;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  content?:
    | T
    | {
        'page-hero'?:
          | T
          | {
              variant?: T;
              dark?: T;
              fullHeight?: T;
              glow?: T;
              formType?: T;
              tag?: T;
              tagLevel?: T;
              title?: T;
              highlight?: T;
              subtitle?: T;
              secondaryHeading?: T;
              secondaryHeadingLevel?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    tag?: T;
                    id?: T;
                  };
              features?:
                | T
                | {
                    icon?:
                      | T
                      | {
                          source?: T;
                          preset?: T;
                          custom?: T;
                        };
                    text?: T;
                    tag?: T;
                    id?: T;
                  };
              heroImage?: T;
              backgroundImage?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    rel?: T;
                    newTab?: T;
                    isExternal?: T;
                    id?: T;
                  };
              helperLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    icon?: T;
                    rel?: T;
                    newTab?: T;
                    isExternal?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        faqs?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  exitPopup?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        ctaText?: T;
        offerImage?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        metaRobots?: T;
        canonicalURL?: T;
        structuredData?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  readTime?: T;
  author?: T;
  categories?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  relatedMode?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        metaRobots?: T;
        canonicalURL?: T;
        structuredData?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  email?: T;
  image?: T;
  socials?:
    | T
    | {
        x?: T;
        linkedin?: T;
        facebook?: T;
        website?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  content?:
    | T
    | {
        'page-hero'?:
          | T
          | {
              variant?: T;
              dark?: T;
              fullHeight?: T;
              glow?: T;
              formType?: T;
              tag?: T;
              tagLevel?: T;
              title?: T;
              highlight?: T;
              subtitle?: T;
              secondaryHeading?: T;
              secondaryHeadingLevel?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    tag?: T;
                    id?: T;
                  };
              features?:
                | T
                | {
                    icon?:
                      | T
                      | {
                          source?: T;
                          preset?: T;
                          custom?: T;
                        };
                    text?: T;
                    tag?: T;
                    id?: T;
                  };
              heroImage?: T;
              backgroundImage?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    rel?: T;
                    newTab?: T;
                    isExternal?: T;
                    id?: T;
                  };
              helperLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    icon?: T;
                    rel?: T;
                    newTab?: T;
                    isExternal?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        faqs?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        metaRobots?: T;
        canonicalURL?: T;
        structuredData?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-makes_select".
 */
export interface CarMakesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  status?: T;
  content?:
    | T
    | {
        'page-hero'?:
          | T
          | {
              variant?: T;
              dark?: T;
              fullHeight?: T;
              glow?: T;
              formType?: T;
              tag?: T;
              tagLevel?: T;
              title?: T;
              highlight?: T;
              subtitle?: T;
              secondaryHeading?: T;
              secondaryHeadingLevel?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    tag?: T;
                    id?: T;
                  };
              features?:
                | T
                | {
                    icon?:
                      | T
                      | {
                          source?: T;
                          preset?: T;
                          custom?: T;
                        };
                    text?: T;
                    tag?: T;
                    id?: T;
                  };
              heroImage?: T;
              backgroundImage?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    rel?: T;
                    newTab?: T;
                    isExternal?: T;
                    id?: T;
                  };
              helperLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    icon?: T;
                    rel?: T;
                    newTab?: T;
                    isExternal?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        faqs?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        metaRobots?: T;
        canonicalURL?: T;
        structuredData?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  siteName?: string | null;
  siteUrl?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  favicon?: (number | null) | Media;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        label: string;
        navType?: ('link' | 'dropdown') | null;
        link?: {
          linkType?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          /**
           * Full URL including https://
           */
          url?: string | null;
          newTab?: boolean | null;
          rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
        };
        children?:
          | {
              link: {
                label: string;
                linkType?: ('internal' | 'external') | null;
                page?: (number | null) | Page;
                /**
                 * Full URL including https://
                 */
                url?: string | null;
                newTab?: boolean | null;
                rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
                /**
                 * Lucide icon name (optional)
                 */
                icon?: string | null;
              };
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerGroups?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              linkType?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              /**
               * Full URL including https://
               */
              url?: string | null;
              newTab?: boolean | null;
              rel?: ('none' | 'nofollow' | 'sponsored' | 'ugc' | 'nofollow noopener') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    ctaText?: string | null;
    ctaUrl?: string | null;
    backgroundColor?: string | null;
  };
  languages?:
    | {
        code: string;
        label: string;
        /**
         * Flag emoji
         */
        flag?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  contactEmail?: T;
  contactPhone?: T;
  favicon?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        navType?: T;
        link?:
          | T
          | {
              linkType?: T;
              page?: T;
              url?: T;
              newTab?: T;
              rel?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    linkType?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                    rel?: T;
                    icon?: T;
                  };
              description?: T;
              id?: T;
            };
        id?: T;
      };
  footerGroups?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              url?: T;
              newTab?: T;
              rel?: T;
              id?: T;
            };
        id?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        ctaText?: T;
        ctaUrl?: T;
        backgroundColor?: T;
      };
  languages?:
    | T
    | {
        code?: T;
        label?: T;
        flag?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}